name: dartbase
description: A dart-native implementation of the Firebase Admin SDK.
version: 0.1.0
homepage: https://github.com/SwissCheese5/Dartbase-Admin-SDK

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  http: ^0.12.1
  grpc: ^2.1.3
  protobuf: ^1.0.1
  fixnum: ^0.10.11
  googleapis_auth: ^0.2.11
  asn1lib: ^0.6.4
  pointycastle: ^1.0.2
  openid_client: ^0.2.5
  clock: ^1.0.1
  x509: ^0.1.0+1
  gcloud: ^0.7.0+1
  json_annotation: ^3.0.1

dev_dependencies:
  build_runner: ^1.10.0
  json_serializable: ^3.3.0
  test: ^1.14.3
  pedantic: ^1.9.0
  firedart: ^0.8.0+1
